### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by limboden** [limboden/prework-study-guide#1]
# HTML

## User Story
As a boot camp student,
I want the prework notes to be structured on a webpage
so that I can easily find and read information

## Acceptance Criteria
GIVEN a Prework study guide
WHEN I visit the website in my browser
THEN I see four boxes titled HTML, CSS, GIT, JAVASCRIPT, with associated notes listed.

**Comment by wasifwasi** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Prework Study Guide</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      display: flex;
      flex-wrap: wrap;
      justify-content: center;
      align-items: center;
      min-height: 100vh;
      background-color: #f5f5f5;
    }

    .section {
      width: 300px;
      margin: 20px;
      padding: 20px;
      background-color: #fff;
      border-radius: 10px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      text-align: center;
    }

    .section h2 {
      font-size: 1.5rem;
      margin-bottom: 15px;
      color: #333;
    }

    .section ul {
      list-style: none;
      padding: 0;
    }

    .section ul li {
      font-size: 1rem;
      color: #555;
      margin-bottom: 8px;
    }
  </style>
</head>
<body>

  <div class="section">
    <h2>HTML</h2>
    <ul>
      <li>HTML stands for HyperText Markup Language</li>
      <li>Used to create the structure of webpages</li>
      <li>Basic tags: &lt;h1&gt;, &lt;p&gt;, &lt;div&gt;, &lt;ul&gt;, &lt;li&gt;</li>
    </ul>
  </div>

  <div class="section">
    <h2>CSS</h2>
    <ul>
      <li>CSS stands for Cascading Style Sheets</li>
      <li>Used for styling and layout of webpages</li>
      <li>Basic properties: color, font-size, margin, padding</li>
    </ul>
  </div>

  <div class="section">
    <h2>Git</h2>
    <ul>
      <li>Git is a version control system</li>
      <li>Allows you to track changes to code</li>
      <li>Commands: git clone, git add, git commit, git push</li>
    </ul>
  </div>

  <div class="section">
    <h2>JavaScript</h2>
    <ul>
      <li>JavaScript is a programming language for web development</li>
      <li>Used to create interactive elements on webpages</li>
      <li>Concepts: variables, functions, events, loops</li>
    </ul>
  </div>

</body>
</html>
`

**Comment by limboden** [comment]
closed
